huh_encore:
    js_entries:
        - { name: contao-twentytwenty-bundle, file: "vendor/heimrichhannot/contao-twentytwenty-bundle/src/Resources/public/js/contao-twentytwenty.es6.js", requires_css: true }