services:
  HeimrichHannot\TwentyTwentyBundle\Asset\FrontendAsset:
    public: true
    autowire: true
    calls:
      - [setEncoreFrontendAsset, ['@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset']]

# config/services.yml

  HeimrichHannot\TwentyTwentyBundle\src\Asset\EncoreExtension:
    autoconfigure: true