services:
  HeimrichHannot\TwentyTwentyBundle\Asset\FrontendAsset:
    public: true
    autowire: true
    calls:
      - [setEncoreFrontendAsset, ['@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset']]

  HeimrichHannot\TwentyTwentyBundle\src\Asset\EncoreExtension:
    autoconfigure: true

  huh_utils:
    enable_services: true
